package com.understory.backups

import android.content.Context
import com.understory.security.Crypto
import java.io.File
import java.io.InputStream
import javax.crypto.Cipher

/**
 * Backups vault bootstrap + unlock. Same snake-eats-tail pattern the
 * other suite vaults use: a 32-byte master KEK is generated at first
 * setup, wrapped under the device-credential-bound Keystore key, and
 * persisted on disk as `header.bin`. BiometricPrompt gates every
 * unlock; the released cipher decrypts the wrapped KEK, which then
 * becomes the "passphrase" fed into [AesGcmPassphraseCodec] for every
 * envelope encrypt/decrypt operation.
 *
 * Why this exists: backups was originally the only vault in the suite
 * that asked the user to type a passphrase. That broke the suite's
 * uniform "self-generated master, never typed, never displayed"
 * sovereignty pattern. This module brings backups into line — the
 * master is generated by [Crypto.randomBytes], wrapped under Keystore,
 * and only ever surfaced via the deliberate "reveal recovery key"
 * biometric-gated flow (the snake-eats-tail recovery escape hatch for
 * cross-device decrypt).
 *
 * Cross-device decrypt flow:
 *   1. User on the origin device taps "Reveal recovery key" →
 *      biometric → screen displays the base64 KEK.
 *   2. User physically transfers the string (paper, password manager,
 *      SimpleX message — user's choice).
 *   3. On the destination device, user taps "Decrypt with recovery key"
 *      → enters the base64 string → codec uses it as the passphrase.
 *      Same Argon2id over the salt in the envelope header reproduces
 *      the same operational key as the origin device used.
 *
 * On-disk layout under `ctx.filesDir/`:
 *   header.bin       — wrapped-KEK bundle (1B version + ivLen+iv + ctLen+ct)
 */
object BackupsVault {

    private const val FILE = "header.bin"
    private const val VERSION_V1: Byte = 1

    private const val MAX_IV_LEN = 256
    private const val MAX_WRAPPED_KEK_LEN = 256
    const val MASTER_KEK_BYTES = 32

    fun exists(ctx: Context): Boolean = File(ctx.filesDir, FILE).exists()

    /**
     * Sweep an orphan `*.tmp` left by an interrupted write. Same
     * housekeeping pattern as the other vaults.
     */
    private fun sweepTmp(ctx: Context) {
        runCatching { File(ctx.filesDir, "$FILE.tmp").delete() }
    }

    /** First-time setup. Caller has authenticated via BiometricPrompt. */
    fun create(
        ctx: Context,
        deviceAuthEncryptCipher: Cipher,
    ): UnlockedBackupsVault {
        sweepTmp(ctx)
        val masterKek = Crypto.randomBytes(MASTER_KEK_BYTES)
        try {
            val wrappedKekCt = deviceAuthEncryptCipher.doFinal(masterKek)
            val wrappedKekIv = deviceAuthEncryptCipher.iv
            writeHeader(ctx, wrappedKekIv, wrappedKekCt)
            return UnlockedBackupsVault(masterKek.copyOf())
        } finally {
            Crypto.wipe(masterKek)
        }
    }

    /**
     * Re-bind an existing vault after [android.security.keystore.KeyPermanentlyInvalidatedException]
     * (biometric re-enrollment / lock-screen change destroyed the wrap key —
     * backups.md §8.2). The master KEK is NOT lost: it equals the base64
     * recovery string the user saved at Setup. We decode that string back to
     * the 32 raw KEK bytes, wrap them under a FRESH device-auth Keystore key
     * (the caller has already authenticated to obtain [deviceAuthEncryptCipher]
     * after [Crypto.deleteDeviceAuthKey] cleared the invalidated alias), and
     * rewrite `header.bin`. Every previously-written envelope stays decryptable
     * throughout because it keys off the recovery string, not the wrap key.
     *
     * The caller owns [recoveryChars] and must wipe it; this method decodes a
     * private copy and wipes that.
     */
    fun rebindFromRecovery(
        ctx: Context,
        recoveryChars: CharArray,
        deviceAuthEncryptCipher: Cipher,
    ): UnlockedBackupsVault {
        sweepTmp(ctx)
        val kek = decodeRecoveryToKek(recoveryChars)
        try {
            require(kek.size == MASTER_KEK_BYTES) {
                "recovery key decodes to ${kek.size} bytes, expected $MASTER_KEK_BYTES"
            }
            val wrappedKekCt = deviceAuthEncryptCipher.doFinal(kek)
            val wrappedKekIv = deviceAuthEncryptCipher.iv
            writeHeader(ctx, wrappedKekIv, wrappedKekCt)
            return UnlockedBackupsVault(kek.copyOf())
        } finally {
            Crypto.wipe(kek)
        }
    }

    /**
     * Decode the base64 recovery string ([UnlockedBackupsVault.recoveryChars]
     * form: NO_WRAP|NO_PADDING) back to the raw KEK bytes. Tolerates
     * surrounding whitespace a user may have introduced when transcribing.
     */
    private fun decodeRecoveryToKek(recoveryChars: CharArray): ByteArray {
        val cleaned = String(recoveryChars).trim().filter { !it.isWhitespace() }
        return android.util.Base64.decode(
            cleaned,
            android.util.Base64.NO_WRAP or android.util.Base64.NO_PADDING,
        )
    }

    /** Daily unlock. */
    fun unlock(
        ctx: Context,
        deviceAuthDecryptCipher: Cipher,
    ): UnlockedBackupsVault {
        sweepTmp(ctx)
        val header = readHeader(ctx)
        val masterKek = deviceAuthDecryptCipher.doFinal(header.wrappedKekCt)
        return UnlockedBackupsVault(masterKek)
    }

    /** IV from disk, fed into [Crypto.deviceAuthCipherForDecrypt]. */
    fun ivForUnlock(ctx: Context): ByteArray = readHeader(ctx).wrappedKekIv

    private fun writeHeader(ctx: Context, iv: ByteArray, ct: ByteArray) {
        val out = java.io.ByteArrayOutputStream()
        out.write(byteArrayOf(VERSION_V1))
        out.write(intBE(iv.size))
        out.write(iv)
        out.write(intBE(ct.size))
        out.write(ct)
        atomicWrite(File(ctx.filesDir, FILE), out.toByteArray())
    }

    private data class Header(val wrappedKekIv: ByteArray, val wrappedKekCt: ByteArray)

    private fun readHeader(ctx: Context): Header {
        val f = File(ctx.filesDir, FILE)
        require(f.exists()) { "backups vault not initialised" }
        f.inputStream().use { input ->
            val v = input.read()
            require(v == VERSION_V1.toInt()) { "expected v1 header, got $v" }
            val ivLen = readIntBE(input)
            require(ivLen in 1..MAX_IV_LEN) { "header iv length out of range: $ivLen" }
            val iv = ByteArray(ivLen); input.readFully(iv)
            val ctLen = readIntBE(input)
            require(ctLen in 1..MAX_WRAPPED_KEK_LEN) { "header ct length out of range: $ctLen" }
            val ct = ByteArray(ctLen); input.readFully(ct)
            require(input.read() == -1) { "trailing bytes in header" }
            return Header(iv, ct)
        }
    }

    private fun atomicWrite(target: File, bytes: ByteArray) {
        target.parentFile?.mkdirs()
        val tmp = File(target.parentFile, "${target.name}.tmp")
        try {
            tmp.outputStream().use { it.write(bytes) }
            try {
                java.nio.file.Files.move(
                    tmp.toPath(),
                    target.toPath(),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                    java.nio.file.StandardCopyOption.ATOMIC_MOVE,
                )
            } catch (_: Throwable) {
                if (!tmp.renameTo(target)) {
                    target.delete()
                    check(tmp.renameTo(target)) { "atomic write failed for ${target.name}" }
                }
            }
        } finally {
            runCatching { if (tmp.exists()) tmp.delete() }
        }
    }

    private fun intBE(n: Int): ByteArray = byteArrayOf(
        ((n ushr 24) and 0xFF).toByte(),
        ((n ushr 16) and 0xFF).toByte(),
        ((n ushr 8) and 0xFF).toByte(),
        (n and 0xFF).toByte(),
    )

    private fun readIntBE(input: InputStream): Int {
        val b = ByteArray(4); input.readFully(b)
        return ((b[0].toInt() and 0xFF) shl 24) or
            ((b[1].toInt() and 0xFF) shl 16) or
            ((b[2].toInt() and 0xFF) shl 8) or
            (b[3].toInt() and 0xFF)
    }

    private fun InputStream.readFully(buf: ByteArray) {
        var off = 0
        while (off < buf.size) {
            val n = read(buf, off, buf.size - off)
            require(n >= 0) { "short read" }
            off += n
        }
    }
}

/**
 * Holds the unlocked master KEK in memory. The CharArray view is what
 * actually gets fed to AesGcmPassphraseCodec — base64 of the 32 raw
 * KEK bytes (~43 chars, ~190 bits of entropy after Argon2 derivation).
 *
 * Hygiene: [lock] zeros both the raw bytes and any cached CharArray.
 * The CharArray itself is recomputed lazily on each [recoveryChars]
 * call and the caller is expected to immediately wrap it in a
 * [AesGcmPassphraseCodec.PassphraseKey] which takes ownership.
 */
class UnlockedBackupsVault internal constructor(
    private val kek: ByteArray,
) {
    /**
     * Encode the 32-byte master as base64 chars. Caller takes ownership
     * — the returned CharArray must be wrapped (PassphraseKey) and
     * wiped, OR the caller wipes it directly.
     */
    fun recoveryChars(): CharArray {
        val b64 = android.util.Base64.encodeToString(
            kek,
            android.util.Base64.NO_WRAP or android.util.Base64.NO_PADDING,
        )
        val chars = b64.toCharArray()
        // Zero the intermediate String's char buffer best-effort. The
        // String's backing array is not directly accessible, but the
        // local b64 reference goes out of scope at function return.
        return chars
    }

    fun lock() {
        Crypto.wipe(kek)
    }
}
