package com.understory.backups

import android.content.Context
import com.understory.security.Crypto
import java.io.File
import java.io.InputStream
import javax.crypto.Cipher

/**
 * Backups vault bootstrap + unlock. Same snake-eats-tail pattern the
 * other suite vaults use: a 32-byte master KEK is generated at first
 * setup, wrapped under the device-credential-bound Keystore key, and
 * persisted on disk as `header.bin`. BiometricPrompt gates every
 * unlock; the released cipher decrypts the wrapped KEK, which then
 * becomes the "passphrase" fed into [AesGcmPassphraseCodec] for every
 * envelope encrypt/decrypt operation.
 *
 * Why this exists: backups was originally the only vault in the suite
 * that asked the user to type a passphrase. That broke the suite's
 * uniform "self-generated master, never typed, never displayed"
 * sovereignty pattern. This module brings backups into line — the
 * master is generated by [Crypto.randomBytes], wrapped under Keystore,
 * and never displayed or typed.
 *
 * Recovery model (operator directive 2026-07-03 — "the screen is the
 * enemy"): the vault's recovery secret is NEVER rendered and NEVER typed.
 * At create the app self-seals a [com.understory.backup.RecoveryFile] kit
 * (a random recovery key it mints and the user never sees, protecting the
 * KEK material below), encrypted at rest under a non-auth Keystore wrap key
 * that SURVIVES biometric re-enrollment. After a fingerprint / lock-screen
 * change the vault silently re-binds from that sealed kit; only if the kit
 * is gone does the user import an exported recovery FILE (SAF), never a
 * typed key.
 *
 * On-disk layout under `ctx.filesDir/`:
 *   header.bin       — wrapped-KEK bundle (1B version + ivLen+iv + ctLen+ct)
 *   recovery_kit.bin — the self-sealed [com.understory.backup.RecoveryFile] kit
 */
object BackupsVault {

    private const val FILE = "header.bin"
    private const val VERSION_V1: Byte = 1

    private const val MAX_IV_LEN = 256
    private const val MAX_WRAPPED_KEK_LEN = 256
    const val MASTER_KEK_BYTES = 32

    fun exists(ctx: Context): Boolean = File(ctx.filesDir, FILE).exists()

    /**
     * Sweep an orphan `*.tmp` left by an interrupted write. Same
     * housekeeping pattern as the other vaults.
     */
    private fun sweepTmp(ctx: Context) {
        runCatching { File(ctx.filesDir, "$FILE.tmp").delete() }
    }

    /** First-time setup. Caller has authenticated via BiometricPrompt. */
    fun create(
        ctx: Context,
        deviceAuthEncryptCipher: Cipher,
    ): UnlockedBackupsVault {
        sweepTmp(ctx)
        val masterKek = Crypto.randomBytes(MASTER_KEK_BYTES)
        try {
            val wrappedKekCt = deviceAuthEncryptCipher.doFinal(masterKek)
            val wrappedKekIv = deviceAuthEncryptCipher.iv
            writeHeader(ctx, wrappedKekIv, wrappedKekCt)
            return UnlockedBackupsVault(masterKek.copyOf())
        } finally {
            Crypto.wipe(masterKek)
        }
    }

    /**
     * Re-bind an existing vault after [android.security.keystore.KeyPermanentlyInvalidatedException]
     * (biometric re-enrollment / lock-screen change destroyed the device-auth
     * wrap key). The master KEK is NOT lost: it is recovered as raw bytes from
     * the self-sealed [com.understory.backup.RecoveryFile] kit (silent path) or
     * from an imported recovery file (SAF), never from a typed key. We wrap those
     * raw [kek] bytes under a FRESH device-auth Keystore key (the caller has
     * already authenticated to obtain [deviceAuthEncryptCipher] after
     * [Crypto.deleteDeviceAuthKey] cleared the invalidated alias), and rewrite
     * `header.bin`. Every previously-written envelope stays decryptable because
     * it keys off the KEK, not the wrap key.
     *
     * The caller owns [kek] and must wipe it; this method keeps a private copy
     * for the returned unlocked vault.
     */
    fun rebindFromKek(
        ctx: Context,
        kek: ByteArray,
        deviceAuthEncryptCipher: Cipher,
    ): UnlockedBackupsVault {
        sweepTmp(ctx)
        require(kek.size == MASTER_KEK_BYTES) {
            "recovery kit yields ${kek.size} bytes, expected $MASTER_KEK_BYTES"
        }
        val wrappedKekCt = deviceAuthEncryptCipher.doFinal(kek)
        val wrappedKekIv = deviceAuthEncryptCipher.iv
        writeHeader(ctx, wrappedKekIv, wrappedKekCt)
        return UnlockedBackupsVault(kek.copyOf())
    }

    /** Daily unlock. */
    fun unlock(
        ctx: Context,
        deviceAuthDecryptCipher: Cipher,
    ): UnlockedBackupsVault {
        sweepTmp(ctx)
        val header = readHeader(ctx)
        val masterKek = deviceAuthDecryptCipher.doFinal(header.wrappedKekCt)
        return UnlockedBackupsVault(masterKek)
    }

    /** IV from disk, fed into [Crypto.deviceAuthCipherForDecrypt]. */
    fun ivForUnlock(ctx: Context): ByteArray = readHeader(ctx).wrappedKekIv

    private fun writeHeader(ctx: Context, iv: ByteArray, ct: ByteArray) {
        val out = java.io.ByteArrayOutputStream()
        out.write(byteArrayOf(VERSION_V1))
        out.write(intBE(iv.size))
        out.write(iv)
        out.write(intBE(ct.size))
        out.write(ct)
        atomicWrite(File(ctx.filesDir, FILE), out.toByteArray())
    }

    private data class Header(val wrappedKekIv: ByteArray, val wrappedKekCt: ByteArray)

    private fun readHeader(ctx: Context): Header {
        val f = File(ctx.filesDir, FILE)
        require(f.exists()) { "backups vault not initialised" }
        f.inputStream().use { input ->
            val v = input.read()
            require(v == VERSION_V1.toInt()) { "expected v1 header, got $v" }
            val ivLen = readIntBE(input)
            require(ivLen in 1..MAX_IV_LEN) { "header iv length out of range: $ivLen" }
            val iv = ByteArray(ivLen); input.readFully(iv)
            val ctLen = readIntBE(input)
            require(ctLen in 1..MAX_WRAPPED_KEK_LEN) { "header ct length out of range: $ctLen" }
            val ct = ByteArray(ctLen); input.readFully(ct)
            require(input.read() == -1) { "trailing bytes in header" }
            return Header(iv, ct)
        }
    }

    private fun atomicWrite(target: File, bytes: ByteArray) {
        target.parentFile?.mkdirs()
        val tmp = File(target.parentFile, "${target.name}.tmp")
        try {
            tmp.outputStream().use { it.write(bytes) }
            try {
                java.nio.file.Files.move(
                    tmp.toPath(),
                    target.toPath(),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                    java.nio.file.StandardCopyOption.ATOMIC_MOVE,
                )
            } catch (_: Throwable) {
                if (!tmp.renameTo(target)) {
                    target.delete()
                    check(tmp.renameTo(target)) { "atomic write failed for ${target.name}" }
                }
            }
        } finally {
            runCatching { if (tmp.exists()) tmp.delete() }
        }
    }

    private fun intBE(n: Int): ByteArray = byteArrayOf(
        ((n ushr 24) and 0xFF).toByte(),
        ((n ushr 16) and 0xFF).toByte(),
        ((n ushr 8) and 0xFF).toByte(),
        (n and 0xFF).toByte(),
    )

    private fun readIntBE(input: InputStream): Int {
        val b = ByteArray(4); input.readFully(b)
        return ((b[0].toInt() and 0xFF) shl 24) or
            ((b[1].toInt() and 0xFF) shl 16) or
            ((b[2].toInt() and 0xFF) shl 8) or
            (b[3].toInt() and 0xFF)
    }

    private fun InputStream.readFully(buf: ByteArray) {
        var off = 0
        while (off < buf.size) {
            val n = read(buf, off, buf.size - off)
            require(n >= 0) { "short read" }
            off += n
        }
    }
}

/**
 * Holds the unlocked master KEK in memory. The CharArray view is what
 * actually gets fed to AesGcmPassphraseCodec — base64 of the 32 raw
 * KEK bytes (~43 chars, ~190 bits of entropy after Argon2 derivation).
 *
 * Hygiene: [lock] zeros both the raw bytes and any cached CharArray.
 * The CharArray itself is recomputed lazily on each [recoveryChars]
 * call and the caller is expected to immediately wrap it in a
 * [AesGcmPassphraseCodec.PassphraseKey] which takes ownership.
 */
class UnlockedBackupsVault internal constructor(
    private val kek: ByteArray,
) {
    /**
     * A copy of the raw 32-byte master KEK — the material the self-sealing
     * [com.understory.backup.RecoveryFile] kit protects and re-yields. Caller
     * takes ownership and MUST [Crypto.wipe] it. Never displayed; used only to
     * seal / export / re-bind the recovery kit.
     */
    fun kekBytes(): ByteArray = kek.copyOf()

    /**
     * Encode the 32-byte master as base64 chars. Caller takes ownership
     * — the returned CharArray must be wrapped (PassphraseKey) and
     * wiped, OR the caller wipes it directly.
     */
    fun recoveryChars(): CharArray {
        val b64 = android.util.Base64.encodeToString(
            kek,
            android.util.Base64.NO_WRAP or android.util.Base64.NO_PADDING,
        )
        val chars = b64.toCharArray()
        // Zero the intermediate String's char buffer best-effort. The
        // String's backing array is not directly accessible, but the
        // local b64 reference goes out of scope at function return.
        return chars
    }

    fun lock() {
        Crypto.wipe(kek)
    }
}
